## Лабораторная № 1. Задание 1

In [149]:
import pandas as pd

1. Загрузка таблицы html

In [158]:
df = pd.read_html("https://pstu.ru/files/file/Abitur/2025%20final/%D0%A1%D0%A4_%D0%91_%D0%9D_000006978.html")[0]
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,NaN,NaN
3,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,NaN,NaN
4,Подразделение - Строительный факультет,Подразделение - Строительный факультет,Подразделение - Строительный факультет,Подразделение - Строительный факультет,Подразделение - Строительный факультет,Подразделение - Строительный факультет,Подразделение - Строительный факультет,Подразделение - Строительный факультет,Подразделение - Строительный факультет,Подразделение - Строительный факультет,Подразделение - Строительный факультет,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,161,4487807,188,64,58,66,0,СТ -25-4б,№ 07-08/9-С от 07.08.2025,NaN,NaN,NaN,NaN
174,162,3586574,188,40,74,74,0,СТ -25-1б,№ 07-08/9-С от 07.08.2025,NaN,NaN,NaN,NaN
175,163,4291080,187,76,56,55,0,СТ -25-8б,№ 07-08/9-С от 07.08.2025,NaN,NaN,NaN,NaN
176,164,4552275,187,72,54,61,0,СТ -25-7б,№ 07-08/9-С от 07.08.2025,NaN,NaN,NaN,NaN
177,165,4279402,187,70,59,58,0,СТ -25-7б,№ 07-08/9-С от 07.08.2025,NaN,NaN,NaN,NaN

2. Удаление лишних элементов из таблицы

In [151]:
cols = df.iloc[12].tolist()
df.columns = cols
df_cleared = df.iloc[13:]
df_cleared = df_cleared.reset_index(drop=True)
df_cleared = df_cleared.dropna(axis=1)
df_cleared = df_cleared.drop(columns=['№', 'Уникальный код', 'Представление приказа', 'Учебная группа'])
display(df_cleared)

,Сумма баллов,АиНМА / Математика,ПФ / Информатика и ИКТ / Физика / Химия,Русский язык,Сумма баллов за ИД
0,264,88,82,94,0
1,262,88,100,74,0
2,258,88,82,88,0
3,256,82,88,86,0
4,254,84,83,87,0
...,...,...,...,...,...
160,188,64,58,66,0
161,188,40,74,74,0
162,187,76,56,55,0
163,187,72,54,61,0
164,187,70,59,58,0

3. Приведение типов

In [152]:
display(df_cleared.dtypes[df_cleared.columns])
df_numeric = df_cleared[df_cleared.columns].astype(int)
print(50*'-')
display(df_numeric.dtypes[df_numeric.columns])

#df_cleared.info()
#print(70*'-')
#df_numeric.info()

Сумма баллов                               object
АиНМА / Математика                         object
ПФ / Информатика и ИКТ / Физика / Химия    object
Русский язык                               object
Сумма баллов за ИД                         object
dtype: object

--------------------------------------------------

Сумма баллов                               int64
АиНМА / Математика                         int64
ПФ / Информатика и ИКТ / Физика / Химия    int64
Русский язык                               int64
Сумма баллов за ИД                         int64
dtype: object

4. Средний, минимальный и максимальный суммарные баллы

In [153]:
#avg_points = (df_numeric['Сумма баллов'].sum() / df_numeric['Сумма баллов'].count()).astype(int)

avg_points = (df_numeric['Сумма баллов'].mean()).astype(int)

min_points = df_numeric['Сумма баллов'].min()

max_points = df_numeric['Сумма баллов'].max()

print("Среднее суммарных баллов = ", avg_points,
      "\nМинимальный суммарный балл = ", min_points,
      "\nМаксимальный суммарный балл = ", max_points)

Среднее суммарных баллов =  209
Минимальный суммарный балл =  187
Максимальный суммарный балл =  264

5. Среднее по предметам

In [154]:
avg_points_math = (df_numeric['АиНМА / Математика'].mean()).astype(int)
avg_points_cpc = (df_numeric['ПФ / Информатика и ИКТ / Физика / Химия'].mean()).astype(int)
avg_points_rl = (df_numeric['Русский язык'].mean()).astype(int)

print('Таблица среднего балла по предметам')

avg_table = pd.DataFrame()
avg_table['АиНМА / Математика'] = [avg_points_math]
avg_table['ПФ / Информатика и ИКТ / Физика / Химия'] = [avg_points_cpc]
avg_table['Русский язык'] = [avg_points_rl]
avg_table.index = ['Балл']

max_avg_points = avg_table.max()
max_avg_sub = avg_table.idxmax(axis=1).iloc[0]
display(avg_table)
print("Предмет с наибольшим средним баллом: ", max_avg_sub)

Таблица среднего балла по предметам

,АиНМА / Математика,ПФ / Информатика и ИКТ / Физика / Химия,Русский язык
Балл,72,67,69

Предмет с наибольшим средним баллом:  АиНМА / Математика

6. Студенты типа 1

In [155]:
type1_count = df_numeric[(df_numeric['Русский язык'] < avg_points_rl) & (df_numeric['ПФ / Информатика и ИКТ / Физика / Химия'] > avg_points_cpc) & (df_numeric['АиНМА / Математика'] > avg_points_math)].shape[0]
print("Количество студентов типа 1: ", type1_count)

Количество студентов типа 1:  16

7. Студенты типа 2

In [156]:
type2_count = df_numeric[(df_numeric['Русский язык'] > avg_points_rl) & (df_numeric['ПФ / Информатика и ИКТ / Физика / Химия'] < avg_points_cpc) & (df_numeric['АиНМА / Математика'] < avg_points_math)].shape[0]
print("Количество студентов типа 2: ", type2_count)

Количество студентов типа 2:  20

8. Новый DataFrame

In [157]:
final_cols = ["Подразделение", "Уровень подготовки", "Направление подготовки/специальность", "Год", "Количество мест", "Предметы ЕГЭ",
"Средняя сумма баллов", "Min сумма баллов", "Max сумма баллов", "Предмет с высшим средним", "Кол-во студентов тип_1", "Кол-во студентов тип_2"]
final_df = pd.DataFrame(columns=final_cols)
final_df['Средняя сумма баллов'] = [avg_points]
final_df['Min сумма баллов'] = [min_points]
final_df['Max сумма баллов'] = [max_points]
final_df['Предмет с высшим средним'] = [max_avg_sub]
final_df['Кол-во студентов тип_1'] = [type1_count]
final_df['Кол-во студентов тип_2'] = [type2_count]

sub_list = df_numeric.columns.tolist()[1:]
final_df['Предметы ЕГЭ'] = [sub_list]

department = df.iloc[4, 0]
department = department.split(' - ')[1]
final_df['Подразделение'] = [department]

level = df.iloc[5, 0]
level = level.split(' - ')[1]
final_df['Уровень подготовки'] = [level]

specialization = df.iloc[6, 0]
specialization = specialization.split(' - ')[1]
final_df['Направление подготовки/специальность'] = [specialization]

year = df.iloc[2, 0]
year = year[26:30]
final_df['Год'] = [year]

place_count = df.iloc[10, 0]
place_count = place_count[12:15]
final_df['Количество мест'] = [place_count]

final_df

,Подразделение,Уровень подготовки,Направление подготовки/специальность,Год,Количество мест,Предметы ЕГЭ,Средняя сумма баллов,Min сумма баллов,Max сумма баллов,Предмет с высшим средним,Кол-во студентов тип_1,Кол-во студентов тип_2
0,Строительный факультет,Бакалавриат,Строительство,2025,165,"[АиНМА / Математика, ПФ / Информатика и ИКТ / ...",209,187,264,АиНМА / Математика,16,20